---
- name: Deploy application
  hosts: all
  tasks:
    - name: Ensure application directory exists
      file:
        path: /var/www/myapp
        state: directory

    - name: Copy application files
      copy:
        src: /local/path/to/app/
        dest: /var/www/myapp/

    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - nginx
        - python3
        - python3-pip

    - name: Start application service
      service:
        name: myapp
        state: started
